### ISSUE TITLE
Blank CSV

### ISSUE THREAD

**Issue by le-travie** [mrrothe/fortilogcsv#1]
Hi, I tried running the converter however the resulting .csv file was blank.

**Comment by mrrothe** [comment]
Hi, are you able to send me a sample of the file you are trying to convert?

**Comment by le-travie** [comment]
> Hi, are you able to send me a sample of the file you are trying to convert?

Sure

**Comment by le-travie** [comment]
[2912232.log](https://github.com/mrrothe/fortilogcsv/files/3752550/2912232.log)
had to trim

**Comment by mrrothe** [comment]
Looks like the format wasn't matching the regex, updated it to deal with more variations and seems to work on your sample. Let me know if that works

**Comment by le-travie** [comment]
Thank you. I'll try it now

**Comment by le-travie** [comment]
It worked! Thank you man, I appreciate it.
