### ISSUE TITLE
Columns being left out

### ISSUE THREAD

**Issue by le-travie** [mrrothe/fortilogcsv#2]
Hi, I have an even longer log file, however, a few columns are being left out. 

[ForwardTrafficLog-disk.log](https://github.com/mrrothe/fortilogcsv/files/3789579/ForwardTrafficLog-disk.log)

**Comment by le-travie** [comment]
I solved the issue. I'll be sharing my method to include the scrip, date and other columns that were missed in the original.

**Comment by le-travie** [comment]
Please see the pattern I used in the .py file attached.
[convert3.txt](https://github.com/mrrothe/fortilogcsv/files/3794178/convert3.txt)

**Comment by mrrothe** [comment]
Hi there, thanks for doing this. I'll take a proper look later and merge the changes.
Martin

**Comment by le-travie** [comment]
No problem
